language: php
php:
  - '7.4'

services:
  - docker

install:
  - composer install --prefer-dist --no-suggest

script:
  - composer ci
  - ./build/build.sh
  - ./build/build_tagged_with_travis_branch_exists.sh
  - ./build/test.sh

cache:
  directories:
  - "$HOME/.composer/cache/files"

deploy:
  provider: script
  script: ./deploy/docker_hub_push.sh
  on:
    tags: true
  skip_cleanup: 'true'
