language: php
php:
- '7.4'

install:
- composer install --prefer-dist

script:
- composer ci

after_success:
- composer compile-phar
- composer test-phar

cache:
  directories:
  - "$HOME/.composer/cache/files"

deploy:
  provider: releases
  api_key:
    secure: gsOOn7rjSVANCfXj/ct22+L7ebpBLihlTO9fX3D4QuxxTz93FLPB6/0rtqMfcpfFGECyaYFiiBlicKzzW19WCh2rYOelQuFJ6+5/OKpiL6fcwGus0vU7q2eUCpRR9Fj6WlyptuN0RfW7cT5tRof+tHEqeGEMXL38gvrJlJ71zLDxC5GScjxBg45IH6yQ3+Gbnzl0dtR+T6N3DC6hzeDvWTdpGUwDi2Ue0AftDMdRTxCrhT4jUjW7F8rriqpv2RcDUBl2nfheVoGRxZNAiXmuPTkezaGZu+JSENxTEn5uDii0bMEiJ4Wn9cVQO5tXf8jxqE/zStATW7IxSY3xw7xKKjEVxmWhxOsY5i6TO7pNlj02eDFH2fcbK5/4n4i+St1gZ2idjzX5M0AznX9BxWZp2leslSfMJiKMDuid8jbLJJJpwpVEBH0f0MUOLqvx6qYB3UZwNI2om5T88IhIopkDT6wJLl/eDHgbRLz6/qIhHaKhaby7MluYwsiljnCKQJsmAo2hfx0Jxaa5qJ4JO/25TP9rYWyaIWThATSziCZKiUV/Whbx8P6Zr95ZOVfzSep5sKLVsGHJ2NArDxhtCdGMnWTaoJhU+jwLfbXkNrEK84zwlu9dbKMczdfjaAPRotMZFB7Jx79kPJm0k5iJq3DexVClf29o4zefYHNx8BbvLs8=
  file: build/compiler.phar
  on:
    tags: true
  skip_cleanup: 'true'
