language: php
php:
  - "7.4"

install:
  - composer install --prefer-dist

script:
  - composer ci

after_success:
  - composer compile-phar
  - composer test-phar

cache:
  directories:
    - $HOME/.composer/cache/files
