language: php
php:
  - '7.4'

services:
  - docker

install:
  - composer install --prefer-dist --no-suggest

script:
  - composer ci
  - cd docker && ./test-build.sh && ./test-run.sh && cd ..

cache:
  directories:
  - "$HOME/.composer/cache/files"
