language: php
php:
  - '7.4'

services:
  - docker

install:
  - composer install --prefer-dist --no-suggest

script:
  - composer ci
  - ./build/build.sh compiler:latest
  - ./build/test.sh compiler:latest

cache:
  directories:
  - "$HOME/.composer/cache/files"
