name: Build Docker Image

on:
  push:
    branches:
      - master
  pull_request:

jobs:
  build:
    name: Create Phar and Build Image
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

#      - name: Set selected color
#        run: echo "::set-output name=SELECTED_COLOR::green"
#        id: random-color-generator
#
#      - name: Get color
#        run: echo "The selected color is ${{ steps.random-color-generator.outputs.SELECTED_COLOR }}"

      - name: Branch name
        run: echo "running on branch ${GITHUB_REF##*/}"

      - name: PR number
        run: echo "$(echo $GITHUB_REF | awk 'BEGIN { FS = "/" } ; { print $3 }')"

      - name: Foo
        id: vars
        run: |
          echo "::set-output name=repo::smartassert/basil-compiler"
          echo "::set-output name=var2::$(echo ${GITHUB_REF})"
          echo "::set-output name=var3::$(echo ${GITHUB_REF##*})"
          echo "::set-output name=tag::$(echo $GITHUB_REF | awk 'BEGIN { FS = "/" } ; { print $3 }')"

      - name: Bar
        run: |
          echo "${{steps.vars.outputs.repo}}"
          echo "${{steps.vars.outputs.var2}}"
          echo "${{steps.vars.outputs.var3}}"
          echo "${{steps.vars.outputs.tag}}"

      - name: Build image
        run: |
          ./build/test_image_exists.sh
        env:
          IMAGE_NAME: ${{steps.vars.outputs.repo}}:${{steps.vars.outputs.tag}}

#      - name: Build Phar
#        run: composer phar-build
#
#      - name: Test Phar
#        run: composer phar-test

#       - name: Build docker image
#         run: ./build/test_image_tests.sh
#         env:
#           IMAGE_NAME: ${{steps.vars.outputs.repo}}

#      - name: Run build script
#        run: |
#          ./build/poc.sh
