name: Build Docker Image

on:
  push:
    branches:
      - master
  pull_request:

jobs:
  build:
    name: Create Phar and Build Image
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set docker image variables
        id: vars
        run: |
          echo "::set-output name=repo::foo"
          echo "::set-output name=tag::$(echo $GITHUB_REF | awk 'BEGIN { FS = "/" } ; { print $3 }')"

      - name: Bar
        run: |
          echo "${{steps.vars.outputs.repo}}"
          echo "${{steps.vars.outputs.tag}}"

#      - name: Build Phar
#        run: composer phar-build
#
#      - name: Test Phar
#        run: composer phar-test

#      - name: Run build script
#        run: |
#          ./build/poc.sh
