name: Build Docker Image

on:
  push:
    branches:
      - master
  pull_request:
  release:
    types:
      - created

jobs:
  build:
    name: Create Phar and Build Image
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Build Phar
        run: composer phar-build

      - name: Test Phar
        run: composer phar-test

      - name: Set image tag name for pull request
        if: ${{ github.event_name == 'pull_request' }}
        id: pull_request_vars
        run: |
          echo "::set-output name=tag::${{ github.event_name }}-${{ github.event.number }}"

      - name: Set image tag name for created release
        if: ${{ github.event_name == 'release' && github.event.action == 'created' }}
        id: release_vars
        run: |
          echo "::set-output name=tag::${{ github.event.release.tag_name }}"

      - name: Echo tester
        run: |
          echo "from pull request"
          echo "${{steps.pull_request_vars.outputs.tag}}"
          echo "from release"
          echo "${{steps.release_vars.outputs.tag}}"

      - name: Build image
        env:
          TAG_NAME: ${{steps.pull_request_vars.outputs.tag}}
        run: |
          ./build/build.sh

      - name: Test image
        env:
          TAG_NAME: ${{steps.pull_request_vars.outputs.tag}}
        run: |
          ./build/test.sh
