name: Build Docker Image

on:
  push:
    branches:
      - master
  pull_request:
  release:
    types:
      - published

jobs:
  build:
    name: Build Docker Image
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set image tag name
        id: vars
        env:
          RELEASE_TAG_NAME: ${{ github.event.release.tag_name }}
        run: |
          [[ ! -z "$RELEASE_TAG_NAME" ]] && echo "::set-output name=tag::$RELEASE_TAG_NAME" || echo "::set-output name=tag::master"

      - name: Build test image
        if: ${{ github.event_name == 'pull_request' }}
        env:
          TAG_NAME: ${{ steps.vars.outputs.tag }}
        run: |
          ./build/build.sh
          ./build/test.sh

      - name: Set up Docker Buildx
        if: ${{ (github.event_name == 'release' && github.event.action == 'published') || (github.event_name == 'push' && github.event.ref == 'refs/heads/master') }}
        uses: docker/setup-buildx-action@v1

      - name: Login to Docker Hub
        if: ${{ (github.event_name == 'release' && github.event.action == 'published') || (github.event_name == 'push' && github.event.ref == 'refs/heads/master') }}
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push image
        if: ${{ (github.event_name == 'release' && github.event.action == 'published') || (github.event_name == 'push' && github.event.ref == 'refs/heads/master') }}
        uses: docker/build-push-action@v2
        with:
          push: true
          tags: smartassert/basil-compiler:${{ steps.vars.outputs.tag }}
