name: Build Docker Image

on:
  push:
    branches:
      - master
  pull_request:

jobs:
  build:
    name: Create Phar and Build Image
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Build Phar
        run: composer phar-build

      - name: Test Phar
        run: composer phar-test

      - name: Set image tag name
        id: vars
        run: |
          echo "::set-output name=tag::$(echo $GITHUB_REF | awk 'BEGIN { FS = "/" } ; { print $3 }')"

      - name: Build image
        run: |
          ./build/build.sh
        env:
          TAG: ${{steps.vars.outputs.tag}}
