name: Build Docker Image

on:
  push:
    branches:
      - master
  pull_request:
  release:
    types:
      - published

jobs:
  build:
    name: Create Phar and Build Image
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Build Phar
        run: composer phar-build

      - name: Test Phar
        run: composer phar-test

      - name: Set image tag name
        id: vars
        env:
          PULL_REQUEST_TAG_NAME: ${{ github.event_name }}-${{ github.event.number }}
          RELEASE_TAG_NAME: ${{ github.event.release.tag_name }}
        run: |
          [[ ! -z "$RELEASE_TAG_NAME" ]] && echo "::set-output name=tag::$RELEASE_TAG_NAME" || echo "::set-output name=tag::$PULL_REQUEST_TAG_NAME"

      - name: Build image
        env:
          TAG_NAME: ${{ steps.vars.outputs.tag }}
        run: |
          ./build/build.sh

      - name: Test image
        env:
          TAG_NAME: ${{ steps.vars.outputs.tag }}
        run: |
          ./build/test.sh
