name: Tests

on:
  push:
    branches:
      - master
  pull_request:

jobs:
  unit:
    name: PHPUnit tests - PHP ${{ matrix.php-versions }} ${{ matrix.operating-system }}
    strategy:
      matrix:
        operating-system: [ubuntu-latest]
        php-versions: ['8']
    runs-on: ${{ matrix.operating-system }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup php
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php-versions }}

      - name: Download dependencies
        uses: php-actions/composer@v2
        with:
          args: --ignore-platform-reqs --quiet

      - name: Run PHPUnit unit tests
        run: composer test-unit

      - name: Run PHPUnit functional tests
        run: composer test-functional

      - name: Run PHPUnit integration tests
        run: composer test-integration

  image:
    name: Test Docker Image
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Build test image
        run: |
          ./build/build.sh
          ./build/test.sh
